#普通数据的配置
name: zhangsan

#对象的配置
#person:
#  name: zhangsan
#  age: 18
#  addr: beijing


#行内对象配置
person: {name: zhangsan,age: 18,addr: beijing}

#配置集合数据(普通字符串)
city:
  - beijing
  - tianjing
  - congqing
  - shanghai
#city: [beijing,tianjing,congqing,shanghai]

#配置集合数据（对象数据）
student:
  - name: tom
    age: 18
    addr: beijing
  - name: lucy
    age: 20
    addr: shanghai
#student: [{ame: tom,age: 18,addr: beijing},{name: lucy,age: 20,addr: shanghai}]

#map配置
map:
  key1: value1
  key2: value2



#springboot基于yml的多环境配置：可以选择激活哪一个配置
server:
  port: 8081
spring:
  profiles:
    active: dev

---
server:
  port: 8082
spring:
  profiles: dev

---
server:
  port: 8083
spring:
  profiles: test
---

debug: true
